### ISSUE TITLE
File name instead of title appearing in sharing function

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1016]
The file name for an HTML upload is appearing in both the reader banner and is also referenced when shared:

<img width="915" alt="banner" src="https://user-images.githubusercontent.com/25825222/39379293-667aff2a-4a20-11e8-9e4f-43d055cf65c4.png">

<img width="587" alt="screen shot 2018-04-27 at 1 28 56 pm" src="https://user-images.githubusercontent.com/25825222/39378919-55548d8e-4a1f-11e8-9a49-870c03c88261.png">

The title of the Text here is simply `Learning from Social Species`. I feel like the project name should replace the file name, and in the share the order should be reversed:

`“Learning from Social Species” in “Social Theory for Nonhumans” on Manifold`

**Comment by SMaxOwok** [comment]
The title in the opengraph tag is determined by the presence/content of the `sectionTitle`, `textTitle`, and `projectTitle`.  

The display conditions/output are currently:
- projectTitle only: `[projectTitle] on [installationName]`
- textTitle & projectTitle are the same: `[sectionTitle] in [projectTitle] on [installationName]`
- textTitle & projectTitle are unique: `[sectionTitle] in [textTitle] on [installationName]`

We could do something like this:
```
“Copyright” in “The Anthrobscene” on Manifold // section, text & project are the same
“Ten Theses for an Aesthetics of Politics: Title Page” in “A different project name” on Manifold // section, text & project are unique
```
One thing to note about this is that there is no way for the reader to know a text was ingested as an html document.  This means that in your case above the output would be `"Learning from Social Species: 02 Ump Stnh" in "Social Theory for Nonhumans" on Manifold`.  In this case, I would say it'd be an important note to people to name their html files as they want them to appear.

The other approach would be to use the project and text, rather than the section and title.  Again, bear in mind that this would affect all texts and mean that we wouldn't see the `sectionTitle` in the opengraph preview at all.

Thoughts @tsmyre?
@zdavis alternate approaches?

**Comment by SMaxOwok** [comment]
@tsmyre I'm closing this in favor of #1040, which I think is what you're requesting at the end of your comment.  If there is still a separate issue here, let me know and I'll reopen.
