### ISSUE TITLE
Page/Location citations in Manifold

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#1206]
## Feature Description
One thing that came up during our Manifold demo at UMP this week is that we don't currently show page or location info in the citation. Some people have asked whether we can include page number info of the cited pass if it was expressed in the ePub. Whether or not that is a possibility, that would not follow existing citation practices, which suggest that you cite the actual thing you are reading, not another version of it (ie, if you are reading a web-based version of a print book, you should cite the web version and not the equivalent print book page numbers). There are ways, however, of citing the web version - -either by citing a paragraph number or perhaps a chapter/section number. 

See, for example:

* https://penandthepad.com/cite-paragraph-numbers-mla-7789001.html

* http://libguides.utep.edu/c.php?g=429836&p=2936576

* https://awc.ashford.edu/cd-in-text-citation-guide.html

If we have a way of indicating paragraph number, then including Chapter name + paragraph number might be a good way to go about this. But this needs further discussion and exploration -- maybe something that one of the grad students working at the GC with me could research.

## *Why* is this feature important? *Who* does it help?
Citations should help people find their way to the source. 

## User Stories
I am a scholar and I quote a section and I want to copy the citation. that citation should be as full as possible and should follow current citation practices.

I am a reading an article and I see a citation of a Manifold publication. I want to find the quotation in the Manifold publication; the paragraph info would help me find the location of the quotation in question.

**Comment by tsmyre** [comment]
Thanks for creating this issue, @mkgold. I surveyed Chicago for their approach, and it very much mirrors your suggestions here: “In practice, because there is always the potential for differences [between the contents of the print and electronic forms], intentional or otherwise, *authors should cite the version consulted*. Chicago recommends including a URL to indicate that a work was consulted online” (emphasis added; CMS 17, 14.16). Our current strategy does not include a URL, so I think that would be good to add, and one that links directly to the passage being cited, if possible.

Regarding the suggestion of referencing the chapter or section, we already do that. It looks like the citation generator is treating texts like contributions to larger works, which I think is the correct approach, so when a cite is generated, you get the author name followed by the name of the text section, and then the title of the text as a whole, followed by some bibliographic details. (The alternative would be to include a chapter number following the bibliographic details, but those won't always be provided or workable, so I'm not keen on that approach here.) So already someone using the generator could navigate between the electronic and print, though, admittedly, not with the same degree of accuracy a page number might provide.

Another option to consider would be to add some search functionality to help address this. In Chicago 1.123 they speak about leveraging the metadata in an EPUB to help readers “locate page numbers referring to the printed book.” Perhaps if a user input a phrase in the search the results could show a print page number alongside the search results, if one was present.

That all said, I think the best first step would be to simply add a URL to the citation generator and review feedback on that approach before devoting further resources to the concern.

**Comment by Cutuchiqueno** [comment]
When I presented Manifold to faculty member this issue was one nearly everyone agreed on and considered essential, more precisely, the possibility to know the paragraph number of a paragraph interest and to have the paragraph number in the generated citation (these are two things), just like @mkgold proposed.

I think this has become quite common practice for citing online sources, look for instance at the [TEI Journal](https://journals.openedition.org/jtei/1746), the [Digital Humanities Manifesto 2.0](http://manifesto.humanities.ucla.edu/2009/05/29/the-digital-humanities-manifesto-20/) or the [Review Journal for Digital Editions and Ressources](https://ride.i-d-e.de/issues/issue-8/phi/).

A paragraph should have a number anchor (if it should be visible or not is another discussion), it should be referencable by a (persistent) URL and should be included in the citation.

**Comment by Cutuchiqueno** [comment]
Just for curiosity, why do you consider this feature as unimportant, or more pragmatically asking, what would be your recommendation for citing a specific part of a text in Manifold?
