### ISSUE TITLE
Error creating new user

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1459]
On the [Emory instance](https://manifold.ecds.emory.edu/), when you add a new user, the following error appears. Despite this error, the new record is created and seems to be functional.

MDS is hosting the Emory instance though it's domain is *not* on manifoldapp.org.

<img width="1568" alt="new-user-error" src="https://user-images.githubusercontent.com/25825222/46685875-2e8bbc80-cbbc-11e8-802c-147f0d64c985.png">

**Comment by zdavis** [comment]
Couple of different issues here... first issue is that for some reason the SMTP config we have in place isn't working. That's weird, since it's working on other instances.

The second issue is that the new user mailer is sending messages in real-time rather than as background jobs, which is what's leading to this exception.

**Comment by zdavis** [comment]
This was due to a misconfiguration in the backend. I've addressed it.
