### ISSUE TITLE
Address Shrine storage problems

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1627]
I'm seeing a few things related to our use of Shrine that I think are problems.

When I ingest a text, I end up with a number of files api/public/system. Some of these files represent the assets in the ingested epub, and are given hashed file names. However, there is no directory structure, which I've seen lead to problems before. These should be stored in directories generated from the IDs.

Second, other files that are attached to IngestionSources are stored in api/public/system/cache. By the name alone, I'd take that directory as something that can be cleaned up—yet it seems to be storing the actual attachment files. Why?

Third, the source file (eg, an EPUB) associated with a text ingestion is being stored without an obfuscated file name. I tend to think we should obfuscate the file names.

As we fix these issues, we need to be very conscious of how this will work with the previous paperclip > shrine migration.

**Comment by scryptmouse** [comment]
For the first and third issues, Shrine has a plugin `pretty_location` that does this.

https://shrinerb.com/rdoc/classes/Shrine/Plugins/PrettyLocation.html

For the second, the cache directory is temporary storage. They should have matching attachments in the actual store directory (sans `cache`), and get deleted upon promotion. It looks like that plugin, though discussed, got left out:

https://shrinerb.com/rdoc/classes/Shrine/Plugins/DeletePromoted.html

It doesn't delete cache automatically because the cache can be a different sort of filesystem entirely from the store / it might be ephemeral / you might want to manage file expiration separately from shrine.

Because of how shrine works (it stores everything needed to find a file related to paths in the JSON), adding these won't affect current uploads but neither will it automatically migrate them. We could generate a migration to just iterate through all the current models with attachments and reupload them from themselves, but it may be overkill and encoding model logic like that in migrations can be problematic.

I added a job during the large upload refactor that deletes cached files older than `2.days` as a future-proofing measure, so that will take care of the ones that didn't get deleted upon promotion.
