### ISSUE TITLE
Set Default Notifications for Administrators and Authors to Daily

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#1668]
## Feature Description
At least as I experienced it, the default notifications are set to no notifications. this is problematic, because people won't know that notifications are even possible unless they receive them. I'd suggest we default to providing notifications, while making it easy for people to dial them back if they would like.

Of course, I come from a perspective of wanting to know more than less, and also from the perspective of running a relatively open installation of Manifold, where I am giving lots of people permission to create Manifold texts and want to notified of new text creations. This is a much different situation than one where a Press is giving just a few people the ability to create projects and have tight control over which ones are created.

## *Why* is this feature important? *Who* does it help?
notifications give project administrators, authors, and editors a sense of what is going on in an installation. as noted above, it's especially important in an instance like CUNY's, where project creation ability is given out widely. 

## User Stories
During a workshop, all attendees are given Project Creator status so that they can experiment with Manifold. Anyone could have attended the workshop, so it is important for the site administrator to be able to know what projects people are creating during the workshop and thereafter. This is one way an instance administrator can help prevent inappropriate content and also texts/images posted without permission

**Comment by zdavis** [comment]
Hey @mkgold, I don't think we're going to turn this on by default for existing accounts—generally speaking, I don't think we should be sending mail without an explicit opt-in on the part of the user, and doing so puts us in conflict with anti-spam best practices.

I think the place to make improvements is in the sign-up process. When you make an account, the first screen has you enter your email, name, and password. Then the user is taken to the edit profile screen, which has a notification button at the bottom. That edit profile screen isn't quite right, because it also has change password fields which don't really make sense in the context of a sign-up. Moreover, the notification settings are buried behind that button.

I think that the solution here is to instead take the user to a different screen during signup that has the avatar upload field and all of the notification settings visible. We could certainly have notification fields enabled by default in this context, which would mean the user would have to un-check them to disable notifications. But we do need the user to see these notification settings and save them before we turn them on, I think.

Please take a look at the sign-up process on edge if any of this is unclear.

**Comment by zdavis** [comment]
I suppose we could enable the notification settings per user in the backend so admins could manually set this up...That would be useful for Matt's use case, and also for cases where a user needed notifications disabled by an admin.

**Comment by zdavis** [comment]
I'm closing this, but have made two smaller issues to capture this request:

#1725
#1726
