### ISSUE TITLE
Adjust height of ingestion output box based on viewport size.

### ISSUE THREAD

**Issue by krosemichael** [ManifoldScholar/manifold#1948]
## Feature Description

The ingest button is not visible on the ingest screen on smaller screens, like laptops,  unless the user scrolls down. Several users at the NYCDH workshop did not realize there was a call to action because they didn't see the green ingest button until we pointed it out to them. 

## *Why* is this feature important? *Who* does it help?

Making the ingest button more obvious, or somehow otherwise indicating there is a call to action at that point in the process would help new users who are ingesting files for the first time.

## User Stories

I am a new user of Manifold using a laptop and ingesting my first text. I have uploaded my text, but the ingestion is not proceeding. I'm not sure what to do because I don't see the ingest button.

**Comment by zdavis** [comment]
Thanks, Krystyna. I'm adding the bug label because no new functionality is requested, and UX problems should be treated as bugs.

I don't think we should redesign this component at this time, but I do think we can adjust the height of the ingestion output textarea based on the size of the user's viewport, which will solve this in most cases. That said, some users on some screens may still end up needing to scroll, because responsive.

**Comment by SMaxOwok** [comment]
Waiting on a quick design pass from Lael.

**Comment by zdavis** [comment]
<img width="1680" alt="Pasted_Image_3_22_19__3_25_PM" src="https://user-images.githubusercontent.com/255909/54856507-2205a700-4cb8-11e9-943a-23fa10187d6f.png">

**Comment by laelito** [comment]
Here's the updated ingest drawer design. It can be found in the latest sketch production file (version 1.8.9).

[BE - Text Ingest Drawer.pdf](https://github.com/ManifoldScholar/manifold/files/3031406/BE.-.Text.Ingest.Drawer.pdf)
