### ISSUE TITLE
TOC Call-to-Action opens to wrong section

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2028]
I understand that the desired behavior for the call-to-action TOC event is to open a manifest ingest to the start section for the text. Using [this manifest](https://github.com/ManifoldScholar/manifold/files/2968854/manifest.zip), that doesn't happen. 

I suspect that's because I have the start section associated with `word-tester.docx`, which appears twice in the manifest. Manifold opens to the second instance, which also happens to be the last text-section of the text.

**Comment by SMaxOwok** [comment]
I don't think this is necessarily a bug nor something we should attempt to support.  This is easily resolved by giving each file a unique name.  Having the same source file appear multiple times in a manifest/TOC will lead to other weird behavior because we expect uniqueness to identify sources.

<img width="556" alt="Screen Shot 2019-03-15 at 8 28 02 AM" src="https://user-images.githubusercontent.com/8389445/54442770-7cbd6280-46fc-11e9-8051-2f614d3fb744.png">

**Comment by tsmyre** [comment]
I don't disagree. This was actually a test intended to see what would happen were I to do this. I don't see a use case where you'd have two documents repeated, but if there were _and_ if they were named the same, it would lead to a problem. In my mind the fix here is on the user side.

**Comment by SMaxOwok** [comment]
Ok, I'm going to close this then.  It did lead to #2029 which is a legitimate bug though.
