### ISSUE TITLE
Support a custom stylesheet during word doc ingestion

### ISSUE THREAD

**Issue by krosemichael** [ManifoldScholar/manifold#2031]
## Feature Description

If there is a stylesheet in a word ingestion (name TBD) we will replace the default word styles with the contents of that stylesheet.

## *Why* is this feature important? *Who* does it help?

This would help users who are ingesting Word docs with images that they would like to caption.

## User Stories

I am a professor who is creating a textbook in Word. My textbook has images with captions that I would like to display in Manifold.

**Comment by zdavis** [comment]
Turns out we kind of misunderstood what the reference document does in Pandoc. It's for going from HTML to Word, not vice versa. The solution here instead will be to allow word docs ingestion to include a custom stylesheet. I'm rewording the issue to reflect this.

**Comment by zdavis** [comment]
I'm not convinced this is worth the effort at this time. I think few users will use this feature, and those who would could just as easily add the custom stylesheet to the text after ingestion. I don't think adding custom stylesheet support will really help with captions for most professors, because they will lack the knowledge to include the stylesheet.Moreover, is it really easier to include the stylesheet at ingestion time than it is to add it in the backend? My view is that we should not proceed with this feature.

The underlying ask—"I want captions to work in word doc ingestion"—probably isn't actionable either, as it seems more a concern up Pandoc than Manifold. Thoughts?

**Comment by tsmyre** [comment]
I actually think something like this would be a very handy feature, but my use case is somewhat different. For publishers who are using custom Word styles—created manually or loaded by way of a Word template—the structuring they are doing as part of their process is presently lost when a text is ingested.

If I were to take a final manuscript here at Minnesota and load it into Manifold, none of the paragraph styles I've assigned the elements of the text persist. If they could be brought in as classes however, I could then load a stylesheet after ingestion and alter the rendering to meet my expectations.

For example, say, in Word, I had something like this:

```
ct     This is the Chapter Title
au     Author Name
pf     First paragraph of the chapter
p      Body paragraph
bqf    First para of a block quote
bql    Last para of a block quote
pcon   Continued body para.
```

Ideally I'd like Manifold to retain those style attributes as paragraph classes (<p class="bqf">, e.g.) so that I could later load a stylesheet that would be able to reference them.

I think this would be useful for works in progress as well as for publishers who feel more comfortable in Word than in the HTML/EPUB space.

**Comment by zdavis** [comment]
But this is outside the scope of what Manifold does, which is why I don't want to keep this issue open. Manifold has no control over the word > html conversion, and whether or not word styles are mapped to html element class names. That is an issue for Pandoc to solve, not us, which means that the real issue here is "replace Pandoc with a different doc > html conversion mechanism," which we do not have resources to tackle. 

All that we can do around this at this time is to apply a custom stylesheet, which can currently be done with existing backend interfaces. I continue to think this issue should be closed.

**Comment by mkgold** [comment]
@zdavis can you say more about what you described here 

> Moreover, is it really easier to include the stylesheet at ingestion time than it is to add it in the backend?

Where/how can one do that and where do we have that documented? How would that current strategy differ in outcome/process than what @krosemichael and @tsmyre are proposing here (keeping in mind your point about what is within and outside of the scope of Manifold)?

**Comment by zdavis** [comment]
Likely caused by https://github.com/jgm/pandoc/issues/4785

**Comment by zdavis** [comment]
Conclusion:
1. Text styled in docx as "caption" comes out as text wrapped in a plain `p` tag in HTML converted by Pandoc.
2. By the time it gets to Manifold, there is no way to style it properly.
3. This is an issue in the upstream conversion engine (Pandoc), and not something we can address at this time.

**Comment by tsmyre** [comment]
@zdavis I'm reopening this issue following our team phone call this afternoon and in light of my recent PanDoc experiments that do allow us to have some sway of capture styles and mapping them to HTML classes.

As a recap, I updated my PanDoc to the newest version and then navigated to a directory where I had a sample Word file that we used custom Word styles to describe the different elements within. I then ran this command, utilizing the Styles extension:

```
pandoc boylan.docx --from docx+styles --to html -s -o boylan.html --wrap=preserve
```

That changed the each paragraph into a div while citing the custom Word style from the document, e.g.:

```
<div data-custom-style="p">
<p>The world of the wasteland is too complex to sum up briefly, but it suffices to say that across the films the constant vision is of a world that is dry, fragmented, and violent. The apocalypse that is the setting for the films is never fully explained in the films, but <span data-custom-style="tnw">Mad Max: Road Warrior</span> (1981) and <span data-custom-style="tnw">Mad Max: Beyond Thunderdome</span> (1985) offer vague references to a nuclear war that ended oil-based civilization. Events in these two films as well as <span data-custom-style="tnw">Mad Max: Fury Road</span> also provide implicit evidence of nuclear fallout in the increased cancer rates and environmental damage.</p>
</div>
```

I did a global find/replace and changed the `data-custom-style` to a `class`, added a reference to our standard CSS and got this: `https://edge.manifoldapp.org/read/boylan/section/6b49c8db-ebaf-4a10-9f2c-afde7dbe044f`. My thinking is a publisher could load one or more Word files and include in the zip archive a house CSS they use/adapt for each publication. Manifold would employ the Styles PanDoc extension as well as change the paragraph attributes to classes and then associate the stylesheet with the Word docs by some means—adding code to the HTML transformation or as a user stylesheet for the text(s).

**Comment by zdavis** [comment]
We will tackle this as part of #2118
