### ISSUE TITLE
Translation feature

### ISSUE THREAD

**Issue by rhoadsstevens** [ManifoldScholar/manifold#2055]
## Feature Description
If I had a text in one language (like Italian), it would be interesting if I could click a button and then have that text replaced with a translation of that text (perhaps in English). The idea isn't that Manifold itself would translate anything. It's that I could ingest two texts (one in Italian, one in English) and that on any page I could toggle back and forth between them. 

## *Why* is this feature important? *Who* does it help?
It would help language instructors how have their students translate texts. Or it would help scholars who work in translation and would like to open up discussions with readers about the process of translation.

## Design Notes
The online version of the Loeb Collection presents ancient Greek and Roman texts next to their translations. This is helpful, but I think it would be even more useful if the texts were on top of each other, and I could toggle back and forth.

**Comment by mkgold** [comment]
Thanks so much for this suggestion, Elliott! It's an interesting and provocative one, though not one that is within the scope of our current grant. Should you have a funding source to support development of this, please let us know and we can consider it -- though I do have some concerns about whether or not the feature, as you describe it here, is even possible/in line with the way that Manifold is currently structured. For now, we are going to close this issue and add the tag "needs funding" to it. 

In order to move towards this possible functionality with the current version of Manifold, might you have the source text include, say, one chapter that is in one language, and another that same language in translation? The two texts could then be accessed via the TOC link, and perhaps you could even add some navigation at the top of each chapter page to better enable a one-click movement from translation to translation.
