### ISSUE TITLE
ResourceThumbnails component hides all at narrower widths

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#2144]
I'm not totally sure offhand what is truncating these, but if there are fewer than 3 resources, the thumbnails don't appear on narrower screens.  It ends up leaving a weird space.

![resource](https://user-images.githubusercontent.com/8389445/55997254-c69f5700-5c6e-11e9-995e-f40d339ff0bc.gif)

**Comment by ConnorChristensen** [comment]
@SMaxOwok
@zdavis 

I looked into this and attempted several solutions, all of them had a problem. I listed the possible fixes in the order that would maintain the broadest browser support and would be the easiest to implement. Suggestions are welcome and I think can implement fix 1 or 2.

**Problem**: On a mobile resolution, the CSS hides the last two elements in the resources list. This is fine when there are 10 elements and you only want to show 8, but when there are any less than 8 elements, it will make the grid uneven. If there are 2 or less, it will remove all the elements.

**Attempted fixes**:

1. Remove the 4x4 sizing, since that is the only one that needs 8 images to look complete  
2. A CSS fix that will only show the number of elements you want
3. A React conditional to add a CSS class depending on the screen size

**Problems with the fixes**:

1. This would require modifying the design
2. I think CSS grid can do this, and it has decent support, but it's not as good as flex
3. React appears to be rendering on the server side (`window` is undefined)

**Comment by zdavis** [comment]
@dananjohnson thoughts?

**Comment by dananjohnson** [comment]
Yeah, I think that's right that the `nth-child` approach currently being used isn't workable. If there's a way to limit the number of items displayed in CSS grid, I'm in support of that option, with a reasonable flexbox fallback (like option #1) for unsupportive browsers. Otherwise, just going with option #1 sounds reasonable to me.
