### ISSUE TITLE
The toggle on the light and dark schemes on touch displays requires two taps

### ISSUE THREAD

**Issue by munsonbh** [ManifoldScholar/manifold#225]
iOS 10.2.1

ER: Tapping once on whichever light and dark toggle would trigger the UI change
AR: The user needs to tap twice to get the effect with no visual feedback that that would be needed.

**Comment by zdavis** [comment]
Confirmed. Seems like first tap gives the button an active state, and the second triggers the click event. Probably need to modify the event type here. Note, I wasn't able to reproduce in Chrome iPhone emulator, but was easily able to reproduce on an actual iOS device.

**Comment by naomiyaki** [comment]
It looks like this was due to the hover state on the buttons showing and hiding the check icon wth `visibility: hidden`. iOS adds an extra click on elements where a hover state shows/hides an element. This is helpful of course, if you have an element where hovering shows information (and is maybe not a link otherwise), but here it's simply a preview/cue. As such, changing `visibility` to `opacity` fixed the bug in this case.
