### ISSUE TITLE
Replace 'menu' with a close 'x' in reader

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#229]
On a phone, I think the "Menu" link in the top left of the reader takes up too much space. I find myself expecting the TOC button to live there. I propose replacing it with a close button (like what we had there a few months back) to move the more useful TOC button into a more natural position. Thoughts?

**Comment by laelito** [comment]
Keep in mind that one of the big drivers for the MENU button replacing the X (close) button was for scenarios where a non-signed-in user is linking into a text from an external source. In that scenario, the MENU button gives them valuable context about where they are (they can see the project's name, visit the project's landing page, sign in (or sign up) for an account, or learn about Manifold). With just an X, they lose that context and those options. Even if the close button sends them back to the text's Manifold project page, without the context that the MENU button provides it may be a confusing and inexplicable jump.

On the other hand, maybe we shouldn't be compromising the mobile reading UI based on the hypothetical experience of people without accounts who click on strange URLS. On the _other_ other hand, when I'm using the app as a signed in user, I do appreciate the navigation options that the MENU button provides and I am inclined to think that if we replace those options with a close button it might be a more jarring experience for most readers.

**Comment by zdavis** [comment]
TOO MANY CHOICES.

**Comment by laelito** [comment]
You ever shopped for cereal before?

**Comment by naomiyaki** [comment]
Sorry about that! I meant to add a comment about user testing - which I think might reveal what is helpful here, but I could also cut the horizontal padding on the menu button a lot for mobile, if the main issue is that it's too much space. I do think having a "menu" button as opposed to "x" is valuable for the use-case of a user coming from outside a Manifold app (say a press website). If a user is on a press page and ends up on a reader with an "X" the expected behavior of the button might be a back button, and not a link to Manifold.

**Comment by zdavis** [comment]
Ok. We'll see what users say, but for now I think that the consensus is to leave it as is.
