### ISSUE TITLE
Reports of inability to upload CSV on Windows + Chrome

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#2409]
Error report is from a surface tablet. User reports that when trying to upload a CSV file in the backend on the bulk resource import interface, the file is not recognized.

"We’re having a weird issue here where we can’t load a CSV file for bulk upload on a Windows machine. Same file works just fine on my Mac. Works as in it loads to the backend. With PC it looks like we never selected any file of any kind."

**Comment by dananjohnson** [comment]
@zdavis The problem here is that Windows doesn't recognize the MIME type "text/csv," so the uploaded file's `type` value is an empty string. This causes it to be rejected by `react-dropzone`. (See [#276](https://github.com/react-dropzone/react-dropzone/issues/276) in that repo).

There's a potential workaround suggested [here](https://github.com/react-dropzone/react-dropzone/issues/276#issuecomment-278357061), which is to set the input's `accept` attribute to `"text/*,"`. This isn't ideal, though, and not just because it would allow other `text` file types to be uploaded. Windows considers CSV files to be MIME type `application/vnd.ms-excel`, so they still won't show up in the file browser as files available for upload. 🙄(The `accept` attribute doesn't work period in Edge, so you can upload anything anyway, as long as it's not an unrecognized MIME type like `text/csv`!)

Maybe we could do something with the rejected files in the `onDrop` callback in `client/src/global/components/form/Upload/Base.js`:
```js
handleFileDrop = (acceptedFiles, rejectedFiles) => {
    this.setState({ attachment: acceptedFiles[0], removed: false });
    rejectedFiles.forEach(file => {
      // do something
    });
  };
```

**Comment by zdavis** [comment]
@dananjohnson Can't we just adjust the upload component so that it also accepts application/vnd.ms-excel?

```
    csv: {
      accepts: "text/plain, text/csv, application/vnd.ms-excel ",
      extensions: "txt, csv"
    },
```

Will that solve the problem?

ZDz

**Comment by dananjohnson** [comment]
@zdavis This doesn't work in Edge. (I still need to confirm IE11.) I can only get it to work there with [this workaround](https://github.com/react-dropzone/react-dropzone/issues/276#issuecomment-278357061), or by setting `accepts` to `null`. I suspect the workaround works because the comma at the end of the string `"text/*,"` invalidates the whole thing in Edge (while still working in other browsers). The issue seems to be that Edge can't set a MIME type when the file is uploaded, and so if anything is set in that `accept` attribute, react-dropzone will just reject the file.

**Comment by zdavis** [comment]
I think the workaround is fine—we check the mime-type server side as well, so there is a fallback if it’s not csv

Zach

------------------------------ 
Zach Davis 
Senior Developer, Majority Partner 
Cast Iron Coding, Inc 
zach@castironcoding.com 
Phone: 971.242.2802 x205

**Comment by murraycollingwood** [comment]
It is now October 2020 and it would appear this is still a problem.
Recently I noticed that my customers (and possible not some customers) have been uploading files of varying types to my server.  While it is relatively safe as the uploaded files are never accessible by the web server I was still concerned about files like *.pkg being uploaded.
So I implemented html like this: 
`<input type="file" name="ifile" id="ifile" accept=".csv, text/csv, text/*,">`
The "text/*," has just been added and I'm hoping this will work around the issue.
However, 12 months since this was first reported and it's still not working correctly.

Does this issue need to be reopened?

**Comment by zdavis** [comment]
I can't tell from your message whether you're actually seeing uploads of `.pkg` files through Manifold or if you're expressing a hypothetical concern. If you have a reproduce case or evidence that Manifold allows a `.pkg` file to be uploaded and stored on the server, I'd like to know more about that, including where it ended up being stored in the file system. Uploads are handled by Manifold's server-side API, which should be validating what's being uploaded. The client-side validation that happens in the input's `accept` attribute is validation that happens in the browser, and as such is not to be trusted. That validation is mainly there just to inform the user that the file they're uploading won't be accepted by the server-side application and is not a security measure.

Manifold has a whitelist of allowed mime types and file extensions, and `.pkg` files are not something that we allow. If that file was uploaded through Manifold, then we need to explore why the validations weren't applied properly. See https://github.com/ManifoldScholar/manifold/blob/master/api/config/manifold.yml#L170 for that white list.

**Comment by murraycollingwood** [comment]
@zdavis The description above is correct.

1. I created a form wanting customers to upload CSV files.  The html looked like this: <input type="file" name="ifile" id="ifile">
2. I then found some Customers were uploading dubious files (like .pkg) 
3. I then modified the html to:  <input type="file" name="ifile" id="ifile" accept=".csv, text/csv">
4. At this point Chrome was working correctly on OSX.  On Windows however customers were trying to upload a valid CSV file but the client side validation was failing with the message about an incorrect mimetype.  NOTE: This is the problem I thought was being solved.
5. After reading the above I have now modified my html to: <input type="file" name="ifile" id="ifile" accept=".csv, text/csv, text/*,">   I'm hoping this will allow Chrome on Windows to accept CSV files.  I understand this is a temporary work around and not a solution.

My understanding is, the client side validation should be correctly identifying a CSV file using the values ".csv" or "text/csv".  It is doing this correctly for Chrome on OSX but failing for Chrome on Windows.

**Comment by zdavis** [comment]
Is your issue related to Manifold Scholarship, which is what this issue tracker is about? Or are you just talking about HTML forms generally?

**Comment by murraycollingwood** [comment]
Sorry, I just noticed I'm in the wrong repository.

**Comment by zdavis** [comment]
No worries.
