### ISSUE TITLE
Remove excess left margin in backend entity header

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#254]
![screen shot 2017-04-07 at 12 12 23 pm](https://cloud.githubusercontent.com/assets/255909/25048591/16011dc0-20f2-11e7-9f09-8b0b0edc4434.png)

Keep in mind, many entities (Resources, for example) allow Markdown in the title, and render it in this header.

**Comment by naomiyaki** [comment]
It looks like in early days we were using a generic <span> selector to grab the subtitles in these headers, but due to the lack of class selector it applied itself to these ingested headers with <span> tags. Now, these headers require a "subtitle" class to use the secondary type

![gpu preview 2017-05-04 14-51-21](https://cloud.githubusercontent.com/assets/1628239/25726470/298366c2-30d9-11e7-9755-b5698f342591.png)
 style.
