### ISSUE TITLE
Highlighting near the reader fade highlights entire top portion

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#255]
![top_highlight](https://cloud.githubusercontent.com/assets/255909/25048694/8ea6b92e-20f2-11e7-9f45-eb8e75810f58.gif)

Perhaps another argument for removing the top reader fade, discussed in #227, or perhaps unrelated.

**Comment by naomiyaki** [comment]
This is not necessarily an issue with the fade (although it is caused by it currently) as it is also caused by the header if you remove the fade. When highlighting text, mousing over a non-text element causes everything above or below the cursor to be selected like in your example gif, however moving the cursor past these elements scrolls the window and allows the user to refine the selection: 
![manifold-highlight-issue_past](https://cloud.githubusercontent.com/assets/1628239/25729015/7ac1dd58-30e7-11e7-9c42-8411bc4a7a77.gif)

In short, this is an issue with having fixed menus on the top (and in some cases bottom) of the viewport, where the user needs to highlight in order to scroll the window further. If we were to remove the header, highlight/scrolling would work great: 
![manifold-highlight_without](https://cloud.githubusercontent.com/assets/1628239/25729046/b19a7ea2-30e7-11e7-9a7d-85b876d27ed1.gif)

Because of this, I wonder if having the header (and fixed footer on narrow windows) slide out of view while the user is highlighting. What do you think @zdavis and @laelito ?

**Comment by laelito** [comment]
If the header/footer unobtrusively slide away, and they do so only during the act of text selection (and the corresponding action pop-up menu), I imagine it should be totally fine. One thing I would recommend is that we make the menu transition animations very quick and barely noticeable—i could see how if you are doing a lot of annotating or highlighting that it might become too flashy or intrusive if we draw a lot of attention to the transitions.

**Comment by zdavis** [comment]
This will no longer be an issue once the new reader header design is implemented. Closing.
