### ISSUE TITLE
For installations that only house standalone projects, library pages should 404.

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#2574]
For this feature, I think we'd expose a top-level setting that forced every project in an installation to standalone mode and disabled all non-standalone frontend views. Any request to a frontend page in library mode would trigger a 404 error.

One challenge here is figuring out how we'd manage views that exist outside of projects such as the manage notifications or reading group views.  There are always going to be some views that are neither project views nor library views per se—what frame do these render in?

**Comment by aupress** [comment]
We use Manifold in standalone mode exclusively, as a companion site to our main website. Since stand-alone projects are hidden from the Manifold projects page, the project page looks blank. This creates a usability issue where a visitor might think that Manifold has no publications. It would be great to have the ability to either redirect visitors to the URL of our choice (say to the home page of our main site) or display 404 page.

**Comment by zdavis** [comment]
Closing this as a duplicate. Actual scope of work is documented in #2652
