### ISSUE TITLE
Text URL changes with Reingest

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2617]
On the Minnesota instance I'm noticing that when I reingest a (HTML) text with a single text section the URL I used to originally target the page no longer works and instead throws an error.

Here's a case to use to replicate the behavior.

In the BE locate a specific text and click the preview button. In this case I'm working on _The Lab Book_, specifically the interview with Andreas Treske. I click the preview button and am awarded this URL in a new window, with everything working as expected: `https://manifold.umn.edu/read/an-interview-with-andreas-treske-of-bilkent-media-archaeology-lab/section/2d26443f-072d-43f8-975a-b1c953e9928d`.

I am making a small correction to the text, so I create my zip archive and reingest it.

After the ingestion is complete, I click the refresh button in the window that opened when I clicked preview, noted above. The refresh throws the following error:

<img width="1509" alt="refresh" src="https://user-images.githubusercontent.com/25825222/74687514-36894280-519a-11ea-8749-f5ac0bc9f38c.png">

In the BE I click the preview button again and the URL now reads as follows: `https://manifold.umn.edu/read/an-interview-with-andreas-treske-of-bilkent-media-archaeology-lab/section/b55aa454-3bb9-4166-9e7b-0d05c3104c08`. The UUID following `section` in the URL has changed.

**Comment by tsmyre** [comment]
During this reingest process I also noticed that placed resources are being lost. The text associated with this archive had a handful of image resources placed, all lost after being reingested.

[stone.zip](https://github.com/ManifoldScholar/manifold/files/4216497/stone.zip)

**Comment by zdavis** [comment]
Placed resources would be lost if the text_section ID changed. The changing ID means Manifold is creating a new text section rather than updating the old one.

That said, I'm unable to reproduce this issue locally or on our edge instance.

To attempt to reproduce, I'm ingesting the stone.zip file that you uploaded. I have a second version of that archive (stone_modified.zip). In the modified version I changed some text in ml60-stone.html. When I reingest it, everything works as it should.

I wonder if you're changing the file name between ingestions? If so, that could be what's causing the problem.

[stone.zip](https://github.com/ManifoldScholar/manifold/files/4237586/stone.zip)
[stone_modified.zip](https://github.com/ManifoldScholar/manifold/files/4237585/stone_modified.zip)

**Comment by tsmyre** [comment]
The file names in the archive didn't change, though the zip archive name _was_ changed. That said I've done that in the past with no effect. And in terms of the files themselves, the only modification made was on line 12 of the HTML:

```html
<p class="au">Interview by Darren Wershler, Lori Emerson, and Jussi Parikka</p>
```

And at that I simply switched the order of the author names.

**Comment by zdavis** [comment]
I'm not sure how that could lead to the outcome you describe. Are you able to reproduce it? And, if so, could you give me the original and revised ingestion sources that can be used to reproduce the problem?

**Comment by tsmyre** [comment]
Okay, so I did just reproduce it on the Minnesota instance. The texts in question have been on the site long enough that they predate the `Download Source` button.

In this instance I went to my file archive on Google Drive and downloaded the source files I originally used to create the text, which you can [access here](https://github.com/ManifoldScholar/manifold/files/4238069/Original.zip).

I then made a slight modification to the HTML, adding one word to the byline, going from "Interview by" to "Interview conducted by"—nothing else. The modified archive [is here](https://github.com/ManifoldScholar/manifold/files/4238078/Archive.zip).

The reingest happened without incident, but now the URL is different and the resources are gone.

Orignial URL: `https://manifold.umn.edu/read/humanities-infrastructure-inflection-and-imagination/section/cc7eea7f-8237-4862-9bae-798ee4c22d11`
New URL: `https://manifold.umn.edu/read/humanities-infrastructure-inflection-and-imagination/section/0902b67c-359e-4db8-a4e1-3ac92a63b592`

**Comment by zdavis** [comment]
Narrowed this down a bit more. To reproduce, you need to be reingesting a source document over a  text that was ingested in Manifold v1 (we refactored in v2). My hunch is that in v1 we based the source identifier off of a different path. This may only be an issue for HTML ingestions:


v1 https://github.com/ManifoldScholar/manifold/blob/v1.0.x/api/app/services/ingestor/strategy/html/inspector/ingestion_source.rb#L16
```
          def source_identifier
            Digest::MD5.hexdigest(rel_path)
          end
```

v2
https://github.com/ManifoldScholar/manifold/blob/master/api/app/services/ingestions/strategy/document/ingestion_source.rb#L21
```
        def source_identifier
          Digest::MD5.hexdigest source_path
        end
```

It's possible that source_path is different from rel_path.

I'm not sure how widespread this issue is. It should only happen for texts that were ingested from documents in v1 or earlier.
