### ISSUE TITLE
Links in HTML ingests fail to properly reference text section

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2787]
Manifold fails to properly reference text sections when transforming internal links during an HTML ingest. For example, this code is for an endnote in the body of a text:

```html
<a id="en3r" role="doc-noteref" class="enref" href="ump-figueroa-0001.html#en3">3</a>
```

That reference should point to the following note at the end of the document:

```html
<p class="en"><a id="en3" role="doc-backlink" class="ennum" href="ump-figueroa-0001.html#en3r">3.</a>	Calkins, L. (2000). The Art of Teaching Reading. London, England: Longman.</p>
```

However, the link in the body of the text in Manifold shows as the following, which throws a 404 error when clicked.

```html
https://edge.manifoldapp.org/read/chapter-two-sarny-and-ourselves/section/ump-figueroa-0001.html#en3
```

Instead, I would expect the link to be transformed to something like this:

```html
https://edge.manifoldapp.org/read/chapter-two-sarny-and-ourselves/section/fa60a515-60ee-4a4a-977c-e5ef368f1bb1#en3
```

It looks like the file name is persisting in the target address instead of the section UUID.

[This archive](https://github.com/ManifoldScholar/manifold/files/4913788/linking.zip) is an example that demonstrates this behavior.

**Comment by zdavis** [comment]
I think this is going to be more trouble than it's worth to fix in code, and we should solve it in documentation instead. When the document ingestion strategy is used, Manifold renames the document being ingested to index.html early in the ingestion process. Mapping URIs in HTML to Manifold URIs is part of the post-processing stage of ingestion. By the time this URI is transformed, Manifold no longer knows what "ump-figueroa-0001.html" refers to, so it can't map it.

I think there are two simple workarounds here:
- The href could be changed to `href="#en3r"`, which is the best solution, since no remapping will be required.
- The href could be changed to `href="index.html#en3r", in which case Manifold would map it to the correct full URL.
