### ISSUE TITLE
Include replies to annotations in reading group dashboard

### ISSUE THREAD

**Issue by krosemichael** [ManifoldScholar/manifold#2838]
## Feature Description
In the reading group dashboard, on the member page, I would like to be able to see and access the replies to annotations as well as original annotations that each member has added to a text.

## *Why* is this feature important? *Who* does it help?
Currently, only annotations that a member of a reading group has created are collected and counted on the "members" page of the reading group dashboard. I would like to be able to see both original annotations and replies to others' annotations in this interface. 

## User Stories
I am an instructor and I have assigned students to create a certain number of annotations as well as a certain number of replies to others' annotations. I would like to be able to see each student's annotations and their replies to others' annotations from the reading group dashboard to make grading easier.

**Comment by imsosickofregisteringforshit** [comment]
This is indeed problematic. I want to be able to easily see how many annotations students have contributed, and since part of their annotations are replies to my own comments, this makes it impossible. Please update! Thx

**Comment by zdavis** [comment]
Not loading comments for annotations in this view is intentional. We don't load comments in lists of annotations for performance reasons. That said, I've added a link to each annotation that will tell you how many comments the annotation has and if you click it, the annotations will load inline.

![image](https://user-images.githubusercontent.com/255909/95638165-904fbd00-0a48-11eb-8f20-2ec46e084873.png)

Clicking "2 comments" will load the comments on that annotation and you can respond inline in the reading group view:

![Uploading image.png…]()

**Comment by zdavis** [comment]
(this will go out in the next major Manifold release, likely v6 — don't have a firm ETA on that yet)

**Comment by mkgold** [comment]
That sounds like a good compromise

**Comment by krosemichael** [comment]
Yes! Beautiful, thank you.
