### ISSUE TITLE
Allow replies to annotations to be associated with a different reading group from the annotation

### ISSUE THREAD

**Issue by krosemichael** [ManifoldScholar/manifold#2847]
## Feature Description

When replying to an annotation, it would be helpful in certain situations to be able to associate the reply with a different reading group from the annotation

## *Why* is this feature important? *Who* does it help?

Allowing replies to annotations to be associated with a different reading group than the annotation would allow instructor to pose questions that could be public, while the replies could be private, and therefore re-usable in different contexts, or public but discoverable by the instructor as parts of different groups.

## User Stories

I am an instructor and I am creating a course text to be re-used from semester-to-semester. I pose questions throughout the text and want my students to answer them in their public reading group as part of an assignment. I want my students' replies to my annotations to be associated with our reading group so that I can see through the reading group dashboard whether they have completed the assignment and give them grades. 

I am an instructor who is re-using a course text, and each semester, my students will be placed in a private reading group. I want their replies to the questions I pose throughout the text in annotations to be associated with our private reading group so that I can give them grades for completing the assignment and so that I can re-use the same questions from semester to semester with each semester's private reading group. 

I am an instructor who has created a course text that is collaborative and/or shared with other instructors at my institution. We pose questions as annotations and want our students in different classes to answer them, in the either public or private reading groups that we are using for other Manifold texts in our respective classes. We want to be able to view and evaluate the responses our own students have written separate from the responses other instructors' students have written. Being able to view their replies as part of our class annotations would allow us to keep our students' work separate while still collaborating with our colleagues on the base text. It would also allow us to keep our students' workflow consistent with the other Manifold texts we are reading this semester in a reading group.

**Comment by imsosickofregisteringforshit** [comment]
I am in the same situation. It would be useful to me if replies could go into a particular reading group even if instructor annotations remain public. Among other things, it creates a weird gradient between students annotations that are public and those that are only available to the reading group.

**Comment by mkgold** [comment]
@imsosickofregisteringforshit Thank you for letting us know that this would be a useful feature for you!!! Those of us at CUNY are focusing on the use of Manifold as a platform for classroom publishing and student engagement. Please continue to share your experiences with us and consider joining the Teaching channel on our Slack space: https://manifold-slackin.herokuapp.com/ . Though that would involve your registering for yet another thing ;)

**Comment by zdavis** [comment]
So, to make sure we're on the same page, let's use the Manifold model names to discuss this. When a user selects text and writes something about it, the user is creating an *annotation*. When a user replies to an *annotation*, the user is creating a *comment*. 

So, we end up with structures like this:

- Annotation
  - Comment A
    - Comment B
  - Comment C

All of the authorization logic (and reading group membership) is associated with the annotation, and that logic is involved, because it touches on whether public annotations are allowed on the instance, whether the user is entitled to see the project, the state of the text (draft or not draft), the user's membership in the annotation reading group, etc. Right now, we can keep our annotations relatively performant because we're only making these considerations in one place, which is on the annotation.  We can also easily render comments because comments have a simple parent/child relationship with the thing being commented on. So, in the example above, the parent of `Comment A` is `Annotation`. The parent of `Comment B` is `Comment A`, and we can easily build out a tree of comments.

What you're proposing here is to give comments two parents: an annotation (or comment) and a reading group. Not only will this add complexity in code, it will make for a difficult UI challenge. What happens if the user belongs to the Comment B reading group, but not the comment A reading group? Do we show the comment without showing the context of the parent comment that it's replying to? I think that will make for bad user experience.

Perhaps students are replying to the instructor annotation when what they should be doing is making their own annotation (which could belong to a different reading group). 

![image](https://user-images.githubusercontent.com/255909/95507512-61f9b100-0966-11eb-8929-c4fbcf70a260.png)

In this screenshot, I have two options. I can "reply" to the existing annotation (which would create a comment). Or, I can press "annotate" to add my own annotation on the text my professor selected. When I do that, I have the option of setting the reading group, because I'm making a new annotation, not replying to an existing one.

![image](https://user-images.githubusercontent.com/255909/95507661-91102280-0966-11eb-987b-10f03f287fb2.png)

It's a subtle, but significant difference. I'm open to proposals to improve the UI or to make this distinction more clear, but I don't think that adding multiple parents to comments is a good idea.

**Comment by krosemichael** [comment]
Honestly, this may be more of an edge case than I first was thinking.  We're using annotations as discussion leading activities - so students are answering in threads, so having them annotate instead of comment on the annotation wouldn't really help, and would be confusing once the first student annotated, since the following comments wouldn't be threaded. Annotations-as-discussion-leading does pose the problem I outline above for professors who want to re-use the text or are sharing it with other professors, but perhaps that isn't a very big population. I'd be curious to hear what others think.

**Comment by zdavis** [comment]
It gets at a problem we've seen come up in a few different ways. When we conceived of the various annotation interfaces, we designed them for individuals annotating individual texts. We've run into a number of problems where this assumption doesn't play out the way we expect in classroom settings where instructors want to reuse materials across different classes without having annotation shared. I'm honestly not quite sure how we solve this problem. With the solution proposed above, you'd still be relying on students to tag their comments in the right reading group, which they likely wouldn't always do. We could allow an annotation to belong to multiple reading groups, and do something where students could only see comments by students in the same reading group, but that's going to get complex too.

We could also make it easier for professors to copy annotations from one text to another. The prof could ingest the text again on a new project and then copy all the annotations from the previous semester text onto the new one. There are downsides to this approach too.

**Comment by krosemichael** [comment]
Yeah I was wondering about that last possibility - making it easier for professors to copy annotations - and perhaps there could be an option to only copy the annotations made by the professor/ user doing the copying, or only annotations but not replies.

**Comment by zdavis** [comment]
The problem with this is that when we build a view, which we plan on doing at some point, that allows a user to list/export all their annotations across all projects, the prof ends up with a bunch of duplicate annotations in the list. Not the end of the world, but not ideal either. Generally speaking, when our data is duplicated, it leads to problems down the road.

**Comment by zdavis** [comment]
We could also shift our thinking around who owns the content on the instance. We could make it so that the owner of a reading group "owns'" the content created in that group, including the replies, and give the reading group owner a button that deleted all replies to his/her annotations.

**Comment by zdavis** [comment]
Anyhow, you see how this is a complex issue that needs more definition before we can really solve for it.

**Comment by krosemichael** [comment]
It's true that students forget to tag their comments in their reading group, so I've been going through and editing them and doing it myself, which isn't that hard if I restrict the view to only public annotations and then just move through them. 

Deleting all the group's replies feels extreme! And a little sad, but might be a good solution to a thorny problem.

But yes, I can see why this is complicated and needs more discussion and definition. Thanks for thinking it through with me.

**Comment by zdavis** [comment]
I'm closing this for now. Happy to see it reopened if we can get it to a clearer, more actionable request that the dev team can work with.

**Comment by mkgold** [comment]
> It gets at a problem we've seen come up in a few different ways. When we conceived of the various annotation interfaces, we designed them for individuals annotating individual texts. We've run into a number of problems where this assumption doesn't play out the way we expect in classroom settings where instructors want to reuse materials across different classes without having annotation shared. I'm honestly not quite sure how we solve this problem. With the solution proposed above, you'd still be relying on students to tag their comments in the right reading group, which they likely wouldn't always do. We could allow an annotation to belong to multiple reading groups, and do something where students could only see comments by students in the same reading group, but that's going to get complex too.
> 
> We could also make it easier for professors to copy annotations from one text to another. The prof could ingest the text again on a new project and then copy all the annotations from the previous semester text onto the new one. There are downsides to this approach too.

Maybe this is something we should try to think through for the NEH grant -- discussing the different kinds of assumptions/use cases teaching/OER use cases bring to Manifold, and where friction arises.

**Comment by zdavis** [comment]
Yes. I don’t know how we fit it into the NEH deliverables, but there is a
need to really come up with a creative solution around reusing materials in
different settings. I don’t yet see a good answer to it, and think we need
to do some brainstorming.

**Comment by imsosickofregisteringforshit** [comment]
Thanks, Zach, for your thoughts about this.


Take care,


Craig

________________________________

**Comment by krosemichael** [comment]
I was just thinking that if the control that allows you to disable public annotations and comments could still allow the author role (or instructor, once that's created) to make public annotations, that would get us part of the way there for using the same instructor annotations with different classes. Private reading groups could still annotate.

I'd imagine commenting on the. public annotations would be disabled and it wouldn't allow reading groups to collaborate, though that could be worked around by doing something like inviting classes to each other's reading groups. It also wouldn't work with public reading groups, so maybe it's not a robust enough solution, but it's an idea.
