### ISSUE TITLE
Add ability to advance through annotations and filter for recency

### ISSUE THREAD

**Issue by krosemichael** [ManifoldScholar/manifold#2872]
## Feature Description

I would like to be able to move from one annotation to the next from within the annotation shelf and filter or sort annotations by time made or recency.

## *Why* is this feature important? *Who* does it help?

This helps someone who would like to view all annotations, or all new annotations, without having to scroll through the text to locate each one.

## User Stories

I am an instructor who would like to quickly read through all of the annotations my class has left on a text. 

I am an author who would like to see what annotations have been left on my text.

## Design Notes

I imagine two possibilities for advancing through annotations -  "next" and "previous" buttons on each annotation, or a scroll of annotations in the annotation shelf.

**Comment by zdavis** [comment]
It would be helpful if you could break this into two issues. The first thing you're asking for—a previous/next link on each annotation—would be implemented in the single annotation component. You might also refine the request a little bit, as it wouldn't actually be moving from one annotation to the next because it's possible for multiple annotations to occupy the same space in the text, in which case they are stacked up in the drawer. What you're asking for, I think, is the ability to navigate to the next annotated spot in the text. It's a subtle distinction, but one that will matter should we build this.

The other request here—ordering annotations by the date they were created—strikes me as a distinct request. Sorting is something that generally can happen in a list. Could you be more specific about which list of annotations you want to to be be to sort? Perhaps you're talking about the annotations list in a reading group, or perhaps in "your notes", or perhaps in the expanded view of "your notes," which are the three places in Manifold where annotations are listed. Or perhaps you mean all three? In any case, each of these is a distinct interface, so we'd want separate issues if you want this functionality in all three views, since it would need to be implemented in slightly different ways for each, since each is a slightly different kind of annotation list.

Thanks!

**Comment by zdavis** [comment]
Another thought on the "recency" request here — sorting by date is a simple ask. If what you really want here is the ability to see "new" annotations, then we would need to build a system that tracks what annotations users have seen. That would be a larger piece of development.

**Comment by zdavis** [comment]
I'm going to close this because I believe it will be addressed as part of the OER work. If, once that work is done, you feel we haven't solved this for you, please don't hesitate to reopen and update.
