### ISSUE TITLE
Ressources -> PDF Links become invalid after a period of time

### ISSUE THREAD

**Issue by Cutuchiqueno** [ManifoldScholar/manifold#2946]
We have a publication that has uploaded PDFs as resources in a resource collection. After the upload the links for the resources work and the reader gets the PDF. However, after a while - and I can only guess for now that it might relate to stoping an starting Manifold again - the links become invalid and I get an error message in the browser.

**Comment by zdavis** [comment]
Could you share some examples of the URLs that aren't working?

**Comment by Cutuchiqueno** [comment]
Today, I corrected them, because it's a publication that is published, new and - at the moment - well attended. Thus, I will have to come back to you in the moment, it happes again. If the reason really is a restart of the app, which I do not know yet for sure, we could also plan it. I will come back to you.

**Comment by zdavis** [comment]
It’s not really possible that restarting manifold could cause a resource
url to no longer work. The data is stored in the database, and the files
are stored in the file system, which are both completely independent from
the app service. Happy to dig into this further, but I would need more
information or steps to reproduce it to take action here. Thanks!

**Comment by Cutuchiqueno** [comment]
Here is a link: https://www.melusinapress.lu/system/cache/resource/0d994b3d-b1f8-46bc-b6f6-593e46d82a5f/attachment/cd19242fa47df0f556e636b47439444f.pdf

2-3 days it was possible to download the PDF after that, it became a dead link again.

I really can not tell what anything about what caused it, but it happened again and again and again. Also we did not change the project or content in the meantime, we did no update, not even a Manifold or a server restart.

**Comment by zdavis** [comment]
Ok, that's helpful. Could you share the PDF with me (feel free to DM it to me on Slack). The file isn't being promoted to persistent storage for some reason—and the temporary storage is cleared periodically. The `cache` segment in the URL is what tells us that it's not being promoted correctly.

**Comment by Cutuchiqueno** [comment]
The abovementioned Link is just one example. It actually happens with all PDFs - but only with PDFs - regardless of the fact if it was produced in our pipeline, using prince-xml or exported by Word. Here are examples for both of these:

[testinventar1.pdf](https://github.com/ManifoldScholar/manifold/files/6121226/testinventar1.pdf)

[lucet_01_Einleitung_ENGL.pdf](https://github.com/ManifoldScholar/manifold/files/6121219/lucet_01_Einleitung_ENGL.pdf)

**Comment by nepella** [comment]
@zdavis: We found the same problem in our Manifold instance (containerized v5.1.3). The cause was that the Manifold_api_sidekiq image is missing Ghostscript: and the `convert` command spawned by the `Attachments::ProcessAttachmentJob` Sidekiq job tries and fails to execute `gs`. (I have the log entries if you want them.)

Would you mind adding Ghostscript to your image? I'm building my own for now. Also, I was able to save about 10 MiB by skipping the recommended and suggested dependencies:

```dockerfile
RUN apt update \
    && apt install --yes --quiet --no-install-recommends --no-install-suggests \
        ghostscript \
    && rm -rf /var/lib/apt/lists/*
```

**Comment by zdavis** [comment]
@nepella Thank you! Any chance you'd like to open a PR on ManifoldScholar/manifold-docker. The file that would need to change is https://github.com/castiron/manifold-docker/blob/master/dockerfiles/manifold_api/Dockerfile

**Comment by nepella** [comment]
@zdavis: Happily! That repo is archived; did you mean [`dockerfiles/manifold-api/Dockerfile` in ManifoldScholar/manifold-docker-build](https://github.com/ManifoldScholar/manifold-docker-build/blob/master/dockerfiles/manifold-api/Dockerfile)?

**Comment by zdavis** [comment]
Sheesh — sorry! Yes, that is exactly what I meant. Thank you! Really appreciate the contribution!

**Comment by nepella** [comment]
@zdavis: Thanks for the invitation; I submitted it [here](https://github.com/ManifoldScholar/manifold-docker-build/pull/23).

**Comment by nepella** [comment]
@zdavis: It occurred to me to check if the omnibus package has the same problem as the Docker image, and it does.

I installed the v5.1.3 package, started Manifold, uploaded a PDF document as a new resource, and found that the attachment wasn't promoted because `gs` was missing. To confirm that the PDF would be deleted, I advanced my test box's clock a few days and edited [api/zhong.rb](/ManifoldScholar/manifold/blob/v5.1.3/api/zhong.rb) to make the Sidekiq job [ExpireShrineCacheJob](/ManifoldScholar/manifold/blob/v5.1.3/api/app/jobs/expire_shrine_cache_job.rb) run every minute; after it ran, the document was gone.

Also, does [this](/ManifoldScholar/manifold/blob/v5.1.3/api/spec/models/resource_spec.rb#L244) test cover attachment promotion?

Thanks!

**Comment by zdavis** [comment]
Thanks again! I'm working on ensuring that GS is present in the omnibus package right now and we'll have it in the next v6 beta release. Really appreciate your help here.

Yes, I would expect that test to cover promotion, although it's not checking for it explicitly. That said, we're not currently running this test on CI (because it's marked as slow). It runs in development environments, but those all have ghostscript, which is why we don't see the problem. We'll work on getting GS in our CI environments and running this test and probably a few others in those envs.

**Comment by zdavis** [comment]
Fixed in https://github.com/ManifoldScholar/manifold-omnibus/commit/1d98bf6c3b49cd7940aa4541bc2a0d7c8e8e713b
