### ISSUE TITLE
Manifold App Failing to Upload 28.5 MB Epub file

### ISSUE THREAD

**Issue by mjohnson92gwu** [ManifoldScholar/manifold#2948]
Hi! I'm a student at GW attempting to upload an epub file to the Manifold app. The app goes through ingestion and it looks like it has added the epub, but when I go to the text list, the new text is not there. I searched my files for unclosed body tags, but do not see any. Could something else be wrong? The file is 28.5 MB. Could it be too large? 
[AOGG Screenshots.docx](https://github.com/ManifoldScholar/manifold/files/6098034/AOGG.Screenshots.docx)

**Comment by tsmyre** [comment]
Hi @mjohnson92gwu! Manifold doesn't have an artificial limit to how large an EPUB can be (we've successfully tested ones as large as 2GB), so I suspect something else may be in play here. My first suggestion would be to validate the file against the EPUB spec [here](http://validator.idpf.org/).

Since this space is geared toward development and the filing of bugs, I'm going to close this issue, and we can pick up the thread over in the [Discussion section](https://github.com/ManifoldScholar/manifold/discussions) of the repo or in [our Slack channels](https://manifold-slackin.herokuapp.com/).
