### ISSUE TITLE
Footer text nav has incorrect top margin

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#308]
![screen shot 2017-05-03 at 1 05 17 pm](https://cloud.githubusercontent.com/assets/255909/25679173/3261d57c-3001-11e7-8770-d8636ab62dee.png)

**Comment by zdavis** [comment]
Right col should not have the top padding.

**Comment by naomiyaki** [comment]
Got it! Will fix when I get a spare moment.

**Comment by naomiyaki** [comment]
Has this been fixed? I'm not able to reproduce on Chrome or Firefox on any window size.

![screen shot 2017-05-04 at 3 02 39 pm](https://cloud.githubusercontent.com/assets/1628239/25726839/d7c5d6d8-30da-11e7-8768-604e680b5d22.png)

**Comment by zdavis** [comment]
It has not, AFAIK. It was an issue as of yesterday or the day before. Add another page record in the rails console `p = Page.create(title: "test page, slug: "test"` and see if you can reproduce. I can't remember exactly what fields are required on Pages, so if it doesn't save, check `p.errors` or `p.valid?` and fix whatever is wrong.

**Comment by naomiyaki** [comment]
I did a bunch of tests with @SMaxOwok and discovered what I believe is the root of the issue. If you take a look at the DOM in your example above, there will likely be an empty <li> tag with a link to a `page` that isn’t showing a `nav_title`. The subsequent <li> has padding on top of it because of sibling spacing. 

I was able to reproduce this repeatedly by creating a new page in the console without a nav_title:
`p = Page.create(title: "Test Page", slug: "test", creator_id: "e126836d-1b19-4ca9-b942-870b64e0a3cc")`. This will ad a valid page, and an empty <li> to the footer menu, even though `show_in_footer` and `nav_title` are nil on the page. This won’t break the layout the first time, but if you add two pages this way (with unique names and slugs), you should see this bug. 
![manifold scholarship 2017-05-04 17-15-28](https://cloud.githubusercontent.com/assets/1628239/25729887/494cee9c-30ed-11e7-90d1-b4ffd68b020c.png)

We can of course address this bug in the view by hiding pages without `nav_title`s and `show_in_footer` in the view, but I wanted to run it by you first before addressing it in the Javascript as Max voiced that some of these fields should be setup as required on the model themselves. That said, if there are going to be pages without nav_titles, I will address that in the view, too! Please advise @zdavis .

**Comment by zdavis** [comment]
Ahh.. ideally, nav_title would be optional and title would be required. We'd show nav_title if set, and fallback to title if it's not set.

**Comment by zdavis** [comment]
Thanks for digging into this one!

**Comment by zdavis** [comment]
This fix is present in the PR according to Naomi. It's lacking any tests, however, and I've asked @SMaxOwok to add them. Accordingly, I'm re-assigning this issue to Max.

**Comment by SMaxOwok** [comment]
Test added
