### ISSUE TITLE
Style issues on users list

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#313]
Opening the drawer bumps the active BG to the left (see screenshot). Also, I think the roles in the right side of the rows are probably not intended to be flush with right edge of container. Please refer to comps.

![screen shot 2017-05-04 at 10 13 59 am](https://cloud.githubusercontent.com/assets/255909/25716041/8751f592-30b2-11e7-8aeb-046dc9e1304f.png)

**Comment by naomiyaki** [comment]
The bump to the active background is in the comps, as is the flush position of the roles, so we'll be adding padding to the active background on the right to match so that the roles aren't flush with the active background in cases where the drawer isn't used.

![screen_shot_2017-05-04_at_10 22 23_am_360](https://cloud.githubusercontent.com/assets/1628239/25716457/f59ad72a-30b3-11e7-8e25-fd1b878ffe06.png)
