### ISSUE TITLE
Numbering does not carry over in two column ordered list (Word doc ingestion)

### ISSUE THREAD

**Issue by bjr70** [ManifoldScholar/manifold#3244]
In uploading a Word doc that has a numbered list split into two columns the numbers repeated in the second column starting at 1 rather than continuing. See the list [here](https://pubhub.lib.msu.edu/read/appendix-e/section/e1b037b3-17b1-484c-8471-80db8dcdf8d7). I worked around this by converting the doc to epub and reingesting, but it would be helpful to have that carryover from the Word doc.

**Comment by zdavis** [comment]
Thanks for the bug report. I'm closing this because it's not something we're going to resolve in Manifold itself. Manifold relies on a library called "Mammoth" for converting Word document to HTML (see https://github.com/mwilliamson/mammoth.js). The issue would need to be addressed in that upstream library for it to be fixed in Manifold.

**Comment by bjr70** [comment]
Thanks! If there isn't an issue for that on Mammoth I'll create it.
