### ISSUE TITLE
Users with scoped roles cannot access journal issues

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#3272]
A user with a global role of reader who has been granted access to a journal issue, by way of a scoped role using the Access sidebar, cannot access the issue/project record they have been granted access: the related project does not appear under the projects menu, and the journal listings return an access denied error.

**Comment by zdavis** [comment]
Confirmed that this is an issue. Will take some days to resolve this. It's on my list.

**Comment by zdavis** [comment]
Hey @tsmyre, this will be fixed in edge soon. Users who have edit access to specific projects that are journal issues will see journals on their dashboard and in the journal list. When they click on the journal, they will only see the issues tab, and only editable issues will be listed. From there, they can click to the corresponding project. Will that work?
