### ISSUE TITLE
Address mobile style issues on user highlights/annotation

### ISSUE THREAD

**Issue by naomiyaki** [ManifoldScholar/manifold#515]
![](https://files.slack.com/files-pri/T068ATVND-F6K9N3QMP/screen_shot_2017-08-08_at_11.23.23_am.png)

**Comment by zdavis** [comment]
Naomi, could you please add more detail to this issue? I'd like to see screenshots, or at the very least documentation of what "issues" this is referring to. Thanks.

**Comment by naomiyaki** [comment]
Thanks Zach,

On mobile, we've got a potential collision with the close button and the title, as well as a z-index fix for the controls (that may be addressed globally by the time I get to this). Let me know when this is actionable!

![Uploading screen_shot_2017-08-08_at_11.23.23_am_720.png…]()

**Comment by zdavis** [comment]
Hey @naomiyaki I still don't understand what this issue is. It looks like you tried to add a screen shot, but it doesn't seem to have worked.

I can't tell from this issue description what component or screen it's referring to. Could you try attaching a screenshot again, and giving us a sample URL or specify the affected component?

**Comment by zdavis** [comment]
@naomiyaki please update. Without more information, this isn't an actionable issue for us. I'm not really sure what "highlights/annotation" refers to in the title. I don't know what component you're talking about in this story.

**Comment by naomiyaki** [comment]
Alright @zdavis ! From what I can tell the title treatment I was thinking of has changed, and it's no longer a bug. Closing.
