### ISSUE TITLE
Rendering and display inconsistencies in resource icons

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#557]
With the current implementation, resource cards do not render reliable or consistently:

![image](https://user-images.githubusercontent.com/255909/30240637-fd0c77a0-9528-11e7-8775-45bf0fdc7020.png)

The amount by which the vertical height is off is dependent on the specific icon, and can be addressed with one-off style declarations in theme/Components/browse/resource/_thumbnail.scss. For example, these rules:
```
    // Hack to make the resource icons the same height on resource cards. --ZD
    &.image {
      margin-bottom: 7px;
    }

    &.audio {
      margin-bottom: 12px;
    }
```
Produce this result:
![image](https://user-images.githubusercontent.com/255909/30240648-3a9d13ea-9529-11e7-8f11-b361cc2c8ce9.png)

Even though this fixes the box layout issue, I believe this is an inadequate fix. While the boxes line up, there are noticeable differences in the size and layout of these icons. For example, the line weight on the document icon is noticeably less on all other icons on the page.

![image](https://user-images.githubusercontent.com/255909/30240691-08920f1c-952a-11e7-912a-d0628b251d92.png)

I realize that not all of our resource icons will necessarily be the same size. Some are landscape and some are portrait orientation. That said, though, we should be able to limit ourselves to two dimensions and work within them. Right now, we end up with sloppy, inconsistent rendering because none of the sizes match.

@naomiyaki and @laelito — can you please prioritize this next week and find the most efficient way to solve this. I don't know if it means redoing some resource icons, or if there is purely a technical fix. I do know that when we render icons in a grid like this, they need to line up as much as possible, and they need to have a consistent look and feel

**Comment by naomiyaki** [comment]
@laelito @zdavis I'm going to have a look at these today and see if I can determine a "bounding box" strategy for these. That is, if the icons can all be sized to fit within a bounding box, we can create that layout constraint in styles. This might involve adding white space to some of the SVGs, which I can totally do. If the icons are too inconsistent, I'll ask Lael about potential revisions.

**Comment by zdavis** [comment]
That sounds great. Thanks, Naomi. Let me know if there's anything I can do to help.

**Comment by laelito** [comment]
@naomiyaki -- that sounds great, thanks.

**Comment by naomiyaki** [comment]
@zdavis @laelito 

I've gone through and determined a bounding box in which all of these icons can fit. The size of the bounding box is, at full size, roughly 68px * 72px

These notes apply to the comp (not the live site)
When the bounding box is centered around the icons, most of them do not line up. The icons aren't really vertically centered, even among like sizes (tall vs wide). I've put together an image to show the following in blue lines:
The top most point that any icon hits
The bottom most point that any icon hits 
The bounding box that could contain all icons, centered around each icon to show relative position.

What we can do:
I think it would be best if Lael could use the AI file I prepared (same as the attached image, only in Illustrator) to either align and/or replace icons as he sees fit. The goal is that we have a bounding box that matches across the board, either top, bottom, or center aligned. The icons can all be different sizes as long as they fit in the same bounding box and follow some logic. Maybe it's ok for them all to be top aligned, I don't know. Once I do, I can output the icons so that they are all consistently sized based on the bounding box and go from there.

If we don't want to adjust the design, I can make the existing layout work, but each icon will need it's own style to place the offset of the bounding box. In general I don't like this solution, especially because it means adjusting new icons every time we add them.

![resource-icon_spacing-original](https://user-images.githubusercontent.com/1628239/30405405-82072570-98a0-11e7-9a6f-06441f7c8cdb.jpg)

**Comment by naomiyaki** [comment]
@zdavis @laelito Was there ever an update on this? Please chime in and I can address asap.

**Comment by zdavis** [comment]
@laelito We need your feedback here to close the loop and finish up this issue. Please chime in.

I think what we'd need you to do is go through these icons and size them so that they fit in a consistent bounding box, as she's done. See above.

Zach

**Comment by laelito** [comment]
@naomiyaki - I went through and adjusted the full suite of icons so that each icon is centered within a 72 pixel square bounding box. I believe this approach solves for the consistency issues while still allowing some flexibility for icon variety. I have also updated the AI file in our shared dropbox.

[Resource_Icon_Spacing_LT.pdf](https://github.com/ManifoldScholar/manifold/files/1364099/Resource_Icon_Spacing_LT.pdf)
