### ISSUE TITLE
Implement Project Collections Functionality

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#771]
## Why do we need this feature?

Projects hosted on Manifold are currently listed in alphabetical order based on the sort title. This naive sorting mechanism does not provide publishers with the tools they need to promote specific projects in the library. Publishers need control over the order of projects within a list.

## User Stories

* As an admin...
  * I see a "manage project library" button on my backend dashboard
  * I can click the "manage project library" button and be taken to the "manage project library" view
  * Using the "manage project library" view...
    * I see a searchable, paginated list of available projects
    * I see a list of projects labelled "Promoted Projects"
    * I see a list of projects labelled "Featured Projects"
    * I can drag an available project into the promoted or featured projects list
    * I can remove a project from the promoted or featured  projects list
    * I can re-sort projects within the promoted or featured  projects list
* As a reader...
  * I see featured projects in their own section, in the specified order
  * I see the promoted projects first in the list of all projects, in the specified order
  * I see non-promoted projects listed after the promoted projects, sorted by last_updated timestamp

## Design Notes

TBD

## Development Notes

TBD

**Comment by susanmpls** [comment]
If a reader is a registered user of Manifold, and is logged in, would the projects they are following supersede the promoted projects? What would be the better reader experience?

**Comment by zdavis** [comment]
I've updated the stories to indicate that this sorting view would also address featured projects.

**Comment by zdavis** [comment]
If we list the followed projects first, we'll be duplicating the functionality on the "following" page. Given that the list of projects is paginated, if a user had favorited 20 projects, she'd see the same list on the home page and the following page, which I think would be bad UX. I think if we put followed projects first, it would be more difficult to expose some readers to new content.

**Comment by susanmpls** [comment]
As a publisher I want to be able to choose which titles appear on the front page of a Manifold installtion. This is true for both the 4 "Featured Projects," and the projects that appear below the feature set, under the "Our Projects" heading.

I want this control because these may be the projects that my publshing house's marketing efforts are currently promoting. Among the reasons for wanting this control: These projects may tie to current events, therefore I want to bring them to the front page from my backlist. These titles may tie-in to a new release (by the same author, on the same topic, etc.) and therefore I want to bring them to the front page from my backlist. These titles may have recently won an award and I want to showcase it/them.

**Comment by susanmpls** [comment]
Presently we have 20 projects that appear under "Our Projects" heading. After scanning those 20 projects, to see more titles (if there are more titles) a reader must click to the next page of the project library. I would like to hear other opinions on this idea, which is that 8 or 12 titles in the "Our Projects" section seems like a more desireable amount. If a reader is interested in scanning all the titles, they will click through to the next page of the library. But more likely, they will want to do a search to find a project that fits with their content need. I don't want to overwhelm them on our front page. Which begs the question: where is the search box on Manifold's front page?

**Comment by zdavis** [comment]
Update on this... we have interactive wireframes we'll be sharing soon that show how we envision this working. @naomiyaki, when you have them, please post them here (if they can be public). Thanks.

**Comment by naomiyaki** [comment]
Hi all,

I'm excited to report that we've put together an interactive prototype for this feature.
I'll go over the basic functionality here, but please feel free to visit the prototype and let me know your thoughts and questions.
https://www.figma.com/proto/GEslgjbg4GrJKSdkksOAahgW/Manifold-Project-Library?scaling=min-zoom&node-id=18%3A377

The prototype has clickable areas which will display in blue when you click anywhere on the prototype (that isn't already a clickable area). The clickable areas link to different slides in the prototype in an effort to illustrate the different views and variants the project groups will have.

Please note that though this prototype uses some existing design elements from the Manifold backend, it should be treated as a high-fidelity wireframe only. Once we've solidified the functionality here, we'll want a thorough design and art-direction from @laelito. 

The prototype illustrates a new model called a "project grouping" and assumes that the backend user can create as many of these as they want, and subsequently adjust the groupings visibility, order, and projects.

There are two types of groupings in the prototype: Smart Grouping, and Manual Grouping
**All Groupings:**
- Can be created
- Can be deleted
- Can be renamed
- Can be manually ordered for display on the front-end
- Can be toggled as visible or invisible on the front-end

**Smart Groupings:**
- Are populated by projects that match a certain criteria/query that the user builds when they create the grouping (it can subsequently be edited as well). 
- Projects cannot be added or removed from Smart Groupings manually, but tags can be used for granular selection of projects. 
- New/edited projects would be automatically added to smart groupings when they match the criteria. Projects will also be removed if they are edited such that they no longer match the criteria. 
- Manual Groupings are populated by searching and selecting projects. 
- Because a smart project list can change automatically, the grouping can only be sorted by criteria (Most recently updated, alphabetical, etc) and not manually.

**Manual Groupings**
- Are populated by searching and selecting projects manually.
- Projects are only added and removed by the backend user.
- Projects can be sorted _either_ manually with drag and drop, or automatically (Most recently updated, alphabetical, etc).

The prototype walks through the flow of
- Adding a new grouping
- Choosing Smart or Manual Grouping (Please experiment and try both!)
- For Smart Grouping
   - Showing a sample query builder and choosing sample input
   - Showing a populated grouping
   - Simulating "edit" button functionality/modal
- For Manual Grouping
  - Showing an empty grouping and adding a sample project
  - Simulating manual vs. automatic ordering
  - Simulating "edit" button functionality/modal
- Simulating "Adding a New Grouping" and starting all over

I look forward to your thoughts and feedback! 
Thank you,
Naomi

**Comment by zdavis** [comment]
Want to make sure @susanmpls, @tsmyre, and @mkgold see this ☝️

**Comment by mkgold** [comment]
Nice work, @naomiyaki !! I really like the "Smart Grouping" and "Manual Group" as a way of thinking about this -- the way you set this up seems really smart to me.

One question I have is whether this will be findable within the dashboard. It's not quite clear to me where one would find the "Project Groupings" settings. The interactive prototype suggests it would be under "Projects," but I wonder whether it should be under "Settings" instead, since that is typically where one would set up the homepage.

Also, I'm wondering whether "Project Groupings" will be a thing for the homepage only or whether you are thinking of it for other areas of the site. If it is only for the homepage, "project groupings" may not be the most intuitive label since it doesn't relate directly to layout or the homepage. If you are thinking about this "grouping" feature more abstractly so that it would be used in other contexts (like, say, placing a "grouping" on a page), that would make more sense.

Those are minor points. Overall, this seems really neat. Nice work!!

**Comment by zdavis** [comment]
We need to be cognizant of #849 as we build out the frontend.

**Comment by zdavis** [comment]
Final designs for this feature are here: https://marvelapp.com/9aeggi1

**Comment by zdavis** [comment]
@susanmpls @tsmyre You may want to take a look at where we landed. I know you've seen earlier iterations of these, but we're now showing the frontend and mobile views as well.

**Comment by tsmyre** [comment]
I think these look fantastic. It looks very easy to use and control on all levels. Ditto for the mobile view. I can easily see myself going in with my phone to do this kind of work on the fly when it's so well laid out. Very very cool. Thanks! And I love the icon choices for the collections.
