### ISSUE TITLE
Drawer notifications should be scoped to the drawer

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#790]
I am creating a new book project in Manifold; while adding an author photo from the book > people interface, I ran into a slightly awkward situation with multiple overlays (see attached screenshot). I had updated the author info and then clicked the pencil icon, which opened the info on the right while the "author updated" overlay was not dismissed at the top.

Not sure whether this is something to address or how (maybe the "update" overlay at the top should disappear once another action is taken, instead of having to be dismissed?) but I wanted to note it.
![screen shot 2018-02-07 at 3 52 07 pm](https://user-images.githubusercontent.com/278503/35941152-52daba58-0c1f-11e8-8221-81be9ff209f3.png)

**Comment by zdavis** [comment]
Thinking about this further, I think we should display drawer notifications in the drawer.

**Comment by zdavis** [comment]
Thanks again for reporting this issue, Matt. 

It's really hard for Manifold to know what action should dismiss a notification. We can't rely on route changes, for example, because there are cases where a notification is triggered right before a route changes (such as when I delete a project and am then redirected to the dashboard). It's going to take some trial and error, I think, to get this really dialed in.

For now, I'm making a few changes to improve the user experience here.

1) Notifications that are triggered from within a drawer should be rendered in the drawer. This would solve the problem shown in your screenshot, in which saving the model triggered a global notification. To accomplish this, we need to revise our notification subsystem to include a concept of scopes or zones in which notifications can render. I've made this change and will be releasing it shortly. Drawer notifications will look like this:

![image](https://user-images.githubusercontent.com/255909/36323849-320efdae-1307-11e8-8288-00d77f6b68f2.png)

2) When the drawer is opened, we should dismiss any global notifications that are still visible. 

I think the combination of these two changes will solve most, if not quite all, global/drawer notification unpleasantness.
