### ISSUE TITLE
Create and Integrate a Manifold Shortlink Generator

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#793]
## Feature Description
This feature would create shortlinks for Manifold publications that could be customized by editors and admins of a Manifold instance

## *Why* is this feature important? *Who* does it help?
Manifold URLs can be a little clunky -- https://cuny.manifoldapp.org/project/how-to-code-in-python-3 . It would be nice if we had a shorturl system (on the CUNY Academic Commons we use cuny.is ) where a shorturl was assigned to a project upon creation, but then could be customized further by the editor/admin. It could perhaps be taken from a hashtag if one were added, or autogenerated or user-entered if not.

## User Stories
I am a Manifold author who can't wait to share my exciting new Manifold publication. But typing out that whole long URL is a bore; I wish I could have an easy-to-remember quicklink that I could share with my peers.

## Design Notes
none from me

## Development Notes
connect to project hashtag?

**Comment by zdavis** [comment]
I get the use case for this, but am not convinced it's Manifold's job to serve as a short link generator. Given how much Manifold is already trying to do, is this something we really want to include, especially when there are preexisting software and service solutions for this?

From a development standpoint, it would introduce complexity across multiple layers. Our packaged distributions, which are already complex, would need to resolve another domain name and map it to a URL resolver service. We'd have to develop an additional service and an interface for managing it. We'd be asking our users to potentially register two domains.

Again, I get that this is useful, I just don't think it's functionality that should sit outside of Manifold, rather than something Manifold should implement.

**Comment by zdavis** [comment]
Agreed on our 5/2/18 call that this isn't where we want to put our efforts right now. Matt may follow up with a separate issue that asks for some improvements to URL structure.

**Comment by mkgold** [comment]
Hi Zach -- just wanted to note that we've had a few requests not necessarily for shortlinks, but rather for neater/shorter links to projects and individual texts. One place this comes up is in citations -- see #2266 which is related, as both have to do with URLs 

In both cases, the issue is that people want to point to their work on Manifold, and/or pointing to one author's contribution to a larger project
