### ISSUE TITLE
EPUB Ingestion fails when a section includes an empty body tag.

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#821]
I just ran into an issue importing an ePub on the CUNY Manifold installation. The file appeared to be ingested, but then did not appear in the list of texts once the ingestion process was finished. I've attached a screenshot of what I saw, and the ePub file is here: https://www.dropbox.com/s/ki0wxx9pkhgpiu6/Ebook%20%281%29.epub?dl=0

I should probably note that this was a re-ingestion of a text that already existed in this project; I was trying to add it as a new text in this case. The ePub file had been edited to remove some of the structural formatting. 

![screen shot 2018-02-27 at 1 57 12 pm](https://user-images.githubusercontent.com/278503/36748628-6ef09d3c-1bc6-11e8-8759-8fb8c98d1c04.png)

**Comment by zdavis** [comment]
At least one section of this EPUB has an empty, self-closing body tag, which is what's triggering this exception. The source of `OPS/content3.xhtml` in the epub, which is the "Class Schedule" section, looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ibooks="http://www.apple.com/2011/iBooks" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:epub="http://www.idpf.org/2007/ops" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml"><head><meta charset="utf-8"/><title>Untitled</title><link rel="stylesheet" type="text/css" href="assets/css/content3.css"/></head><body/></html>
```

We haven't encountered this issue yet, as all the texts we've ingested have had content in every section. I will adjust the HTML validator, which is where the exception is happening, so that it doesn't choke when it's passed a null value.

**Comment by mkgold** [comment]
okay - -thanks, Zach. I've sent the link to this ticket to the ePub creator, and they will hopefully address this in the ePub
